export const listingFieldLabels = {
  title: { en: "Title", jp: "タイトル" },
  monthlyRentYen: { en: "Monthly Rent (JPY)", jp: "月額家賃 (円)" },
  addressText: { en: "Address", jp: "住所" },
  sourceUrl: { en: "Source URL", jp: "掲載URL" },
  reikinMonths: { en: "Key Money (months)", jp: "礼金 (ヶ月)" },
  securityDepositMonths: { en: "Security Deposit (months)", jp: "敷金 (ヶ月)" },
  squareM: { en: "Floor Area (㎡)", jp: "面積 (㎡)" },
  closestStation: { en: "Closest Station", jp: "最寄り駅" },
  walkingTimeMin: { en: "Walking Time (min)", jp: "徒歩 (分)" },
  availability: { en: "Availability", jp: "募集状況" },
  propertyType: { en: "Property Type", jp: "物件種別" },
  interest: { en: "Interest", jp: "関心度" },
  prefecture: { en: "Prefecture", jp: "都 / 県" },
  municipality: { en: "Municipality", jp: "市 / 区" },
  town: { en: "Town", jp: "町" },
  district: { en: "District", jp: "丁目" },
  block: { en: "Block", jp: "番" },
  houseNumber: { en: "House Number", jp: "号" },
} as const;
